namespace: task-platform

ingress:
  host: task-platform.local

authService:
  name: auth-service
  image: auth-service
  tag: latest
  port: 8000
  grpcPort: 50051
  replicas: 1

taskService:
  name: task-service
  image: task-service
  tag: latest
  port: 8000
  replicas: 1

gateway:
  name: gateway
  image: gateway
  tag: latest
  port: 8000
  replicas: 1

redis:
  name: cache
  image: redis
  tag: 7-alpine
  port: 6379

authDb:
  image: postgres
  tag: "15"
  port: 5432

taskDb:
  image: postgres
  tag: "15"
  port: 5432

config:
  algorithm: HS256
  accessTokenExpireMinutes: "30"
  authServiceUrl: "http://auth-service:8000"
  taskServiceUrl: "http://task-service:8000"
  redisUrl: redis://cache:6379
  celeryBrokerUrl: redis://cache:6379/0
  celeryResultBackend: redis://cache:6379/0

secrets:
  SECRET_KEY: UBETi1J7SdoSnsrOfWwSuABc2yiRyeCwIcrhJFv2rOx
  AUTH_DATABASE_URL: postgresql+asyncpg://prakhar:yourpassword@auth-db:5432/auth-db
  TASK_DATABASE_URL: postgresql+asyncpg://prakhar:yourpassword@task-db:5432/task-db
  POSTGRES_USER: prakhar
  POSTGRES_PASSWORD: yourpassword
  POSTGRES_DB: auth-db
  TASK_POSTGRES_USER: prakhar
  TASK_POSTGRES_PASSWORD: yourpassword
  TASK_POSTGRES_DB: task-db