apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: "{{ .Values.namespace }}"
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: "{{ .Values.authDb.image }}"
          image: "{{ .Values.authDb.image }}:{{ .Values.authDb.tag }}"
          ports:
            - containerPort: {{ .Values.authDb.port }}
              name: "{{ .Values.authDb.image }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret-base64
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret-base64
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret-base64
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.authDb.port }}
      targetPort: {{ .Values.authDb.port }}
  selector:
    app: auth-db
