apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authService.image }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.authService.image }}
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.authService.image }}
  template:
    metadata:
      labels:
        app: {{ .Values.authService.image }}
    spec:
      containers:
        - name: {{ .Values.authService.name }}
          image: {{ .Values.authService.image }}:{{ .Values.authService.tag }}
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: task-platform-config
            - secretRef:
                name: my-secret-base64
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.image }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.authService.image }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.authService.image }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051