apiVersion: v1
kind: Secret
metadata:
  name: my-secret-base64
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.secrets.SECRET_KEY }}"
  AUTH_DATABASE_URL: "{{ .Values.secrets.AUTH_DATABASE_URL }}"
  TASK_DATABASE_URL: "{{ .Values.secrets.TASK_DATABASE_URL }}"
  POSTGRES_USER: "{{ .Values.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.POSTGRES_PASSWORD }}"
  POSTGRES_DB: "{{ .Values.secrets.POSTGRES_DB }}"
  TASK_POSTGRES_USER: "{{ .Values.secrets.TASK_POSTGRES_USER }}"
  TASK_POSTGRES_PASSWORD: "{{ .Values.secrets.TASK_POSTGRES_PASSWORD }}"
  TASK_POSTGRES_DB: "{{ .Values.secrets.TASK_POSTGRES_DB }}"