apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.taskService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.taskService.name }}
spec:
  replicas: {{ .Values.taskService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.taskService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.taskService.name }}
    spec:
      containers:
        - name: {{ .Values.taskService.name }}
          image: {{ .Values.taskService.image }}:{{ .Values.taskService.tag }}
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: task-platform-config
            - secretRef:
                name: my-secret-base64
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: {{ .Values.taskService.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.taskService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.taskService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.taskService.name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000