apiVersion: v1
kind: Secret
metadata:
  name: my-secret-base64
  namespace: task-platform
type: Opaque
stringData:
  SECRET_KEY: UBETi1J7SdoSnsrOfWwSuABc2yiRyeCwIcrhJFv2rOx
  AUTH_DATABASE_URL: postgresql+asyncpg://prakhar:yourpassword@auth-db:5432/auth-db
  TASK_DATABASE_URL: postgresql+asyncpg://prakhar:yourpassword@task-db:5432/task-db
  POSTGRES_USER: prakhar
  POSTGRES_PASSWORD: yourpassword
  POSTGRES_DB: auth-db